name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Alternative simple release without GoReleaser
  simple-release:
    runs-on: ubuntu-latest
    needs: goreleaser
    if: always() && needs.goreleaser.result == 'failure'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build for multiple platforms
        run: |
          # Get version from tag
          VERSION=${GITHUB_REF#refs/tags/}

          # Build for different platforms
          GOOS=linux GOARCH=amd64 go build -o subdomainx-linux-amd64 ./cmd/subdomainx
          GOOS=linux GOARCH=arm64 go build -o subdomainx-linux-arm64 ./cmd/subdomainx
          GOOS=darwin GOARCH=amd64 go build -o subdomainx-darwin-amd64 ./cmd/subdomainx
          GOOS=darwin GOARCH=arm64 go build -o subdomainx-darwin-arm64 ./cmd/subdomainx
          GOOS=windows GOARCH=amd64 go build -o subdomainx-windows-amd64.exe ./cmd/subdomainx

          # Create release archive
          tar -czf subdomainx-${VERSION}-linux-amd64.tar.gz subdomainx-linux-amd64
          tar -czf subdomainx-${VERSION}-linux-arm64.tar.gz subdomainx-linux-arm64
          tar -czf subdomainx-${VERSION}-darwin-amd64.tar.gz subdomainx-darwin-amd64
          tar -czf subdomainx-${VERSION}-darwin-arm64.tar.gz subdomainx-darwin-arm64
          zip subdomainx-${VERSION}-windows-amd64.zip subdomainx-windows-amd64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            subdomainx-*-linux-amd64.tar.gz
            subdomainx-*-linux-arm64.tar.gz
            subdomainx-*-darwin-amd64.tar.gz
            subdomainx-*-darwin-arm64.tar.gz
            subdomainx-*-windows-amd64.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
